# Creating and Manipulating NumPy Arrays and Matrices
This notebook should help to get familiar with some of the basic functions and operations in NumPy

Note that all principles in this tutorial can generally be extended to N-dimensional data structures even though it only explicitly uses 1D and 2D data structures

### Import NumPy
First, you'll need to import numpy. There's a standard shorthand for NumPy -- np -- so that's what I'll be using.

In [1]:
import numpy as np

### Creating Vectors and Matrices
NumPy arrays are somewhat ill-defined as to whether they are row or column vectors, so you can add an extra dimension to make it explicit

It is important to remember that vectors are matrices with a size of 1 along one of the axes

In [2]:
# Arrays - 1D data structure
sample_array = np.array([1, 2, 3, 4])
print(sample_array)

[1 2 3 4]


In [3]:
# Row vectors - 2D data structure
sample_row_vec1 = np.array([[10, 20, 30, 40]])
sample_row_vec2 = np.array([11, 12, 13, 14])[np.newaxis, :]
print(sample_row_vec1)
print(sample_row_vec2)

[[10 20 30 40]]
[[11 12 13 14]]


In [4]:
# Column vectors - 2D data structure
sample_col_vec1 = np.array([[100], [200], [300], [400]])
sample_col_vec2 = np.array([101, 202, 303, 404])[:, np.newaxis]
sample_col_vec3 = np.array([[111, 222, 333, 444]]).T
print(sample_col_vec1)
print(sample_col_vec2)
print(sample_col_vec3)

[[100]
 [200]
 [300]
 [400]]
[[101]
 [202]
 [303]
 [404]]
[[111]
 [222]
 [333]
 [444]]


In [5]:
# Matrices - 2D data structure
sample_mat2x2 = np.array([[1, 2], [3, 4]])
sample_mat2x4 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
sample_mat3x2 = np.array([[11, 12], [21, 22], [31, 32]])
print(sample_mat2x2)
print(sample_mat2x4)
print(sample_mat3x2)

[[1 2]
 [3 4]]
[[10 20 30 40]
 [50 60 70 80]]
[[11 12]
 [21 22]
 [31 32]]


### Manipulating Arrays

In [ ]:
# Create a 1D array 